spring.application.name=bankingSystem-springBoot
spring.datasource.url=jdbc:postgresql://dpg-d79sd4p5pdvs73bostkg-a.oregon-postgres.render.com:5432/banking_5h84?sslmode=require
spring.datasource.username=banking_user
spring.datasource.password=jlpp2DIuXh6FB0RiF7E8Ma0DhxLSwndq

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true